
services:
  productdb:
    image: postgres

  cartdb:
    image: postgres

  discountdb:
    image: postgres

  orderdb:
    image: postgres

  distributedcache:
    image: redis

  messagebroker:
    image: rabbitmq:management

  # product.api:
  #   image: ${DOCKER_REGISTRY-}productapi
  #   build:
  #     context: .
  #     dockerfile: Services/Product/Dockerfile

  # cart.api:
  #   image: ${DOCKER_REGISTRY-}cartapi
  #   build:
  #     context: .
  #     dockerfile: Services/Cart/Dockerfile

  # discount.grpc:
  #   image: ${DOCKER_REGISTRY-}discountgrpc
  #   build:
  #     context: .
  #     dockerfile: Services/Discount.Grpc/Dockerfile

  # ordering.api:
  #   image: ${DOCKER_REGISTRY-}orderingapi
  #   build:
  #     context: .
  #     dockerfile: Services/Ordering/Ordering.API/Dockerfile

volumes:
  postgres_product:
  postgres_cart:
  postgres_discount:
  postgres_order: